# PostgreSQL Secret
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # Base64 encoded values (Use 'echo -n "value" | base64' to encode)
  # 'postgres' encoded as base64
  username: cG9zdGdyZXM=
  # 'postgres' encoded as base64 - CHANGE THIS IN PRODUCTION
  password: cG9zdGdyZXM=
---
# Backend Secret
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  # Base64 encoded values - CHANGE THESE IN PRODUCTION
  # 'a-very-secure-secret-key' encoded as base64
  secret-key: YS12ZXJ5LXNlY3VyZS1zZWNyZXQta2V5
  # 'a-very-secure-jwt-secret-key' encoded as base64
  jwt-secret-key: YS12ZXJ5LXNlY3VyZS1qd3Qtc2VjcmV0LWtleQ==